title: Melee Notes
description: A short description of your site's purpose.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://graves-1.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Navigation settings
navigation:
  - title: "Home"
    url: "/"
  - title: "Captain Falcon"
    url: "/captainfalcon"
  - title: "Falco"
    url: "/falco"
